navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png # https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title:
  menu:
- name: 博客
  icon: fa-solid fa-rss
  rows:
    - name: 分类
      url: categories
    - name: 标签
      url: tages
    - name: 时光机
    - url: archives
 - name: 友链
   icon: fa-solid fa-link
   rows:
     - name: 朋友圈
      url: links
     - name: 友链
      url: friends
 - name: 关于
   icon: fa-solid fa-info-circle
   rows:
     - name: 关于本站
       url: /2022/09/24/list/
     - name: 关于
       url: 2022/08/20/about/
  
