debug: false
content_visibility: true
navbar:
  logo: # choose [img] or [icon + title]
    img: '' # volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png
    icon:
    title: '无影博客'
  menu:
    - name: 首页
      icon: fa-solid fa-rss
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: tags/
      rows:  
        - name: gridea
          icon: fas fa-network-wired fa-fw
          url: tags/gridea/
        - name: bilbil
          icon: fas fa-network-wired fa-fw
          url: tags/blibli/
        - name: 学科
          icon: fas fa-network-wired fa-fw
          url: tags/学科/ 
        - name: bilbilpage2
          icon: fas fa-network-wired fa-fw
          url: tags/blibli-page-2/
        - name: 相册集
          icon: fas fa-network-wired fa-fw
          url: tags/相册/     
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 友链
      icon: fa-solid fa-link
      rows:
        - name: 友链
          icon: fa-fw fas fa-link faa-tada
          url: friends/
        - name: 朋友圈
          icon: fa-solid fa-feed fa-fw
          url: links/
    - name: 关于
      icon: fa-solid fa-info-circle
      rows:
        - name: 版权声明
          url: 2022/09/17/copyright/
        - name: 免责声明
          url: 2022/09/17/mian-ze-sheng-ming-1/
        - name: 关于本站
          url: 2022/09/24/list/
        - name: 关于
          url: /2022/08/20/about/
    - name: 更多
      icon: fa-duotone fa-ellipsis-v
      rows:
        - name: 音乐
          icon: fa-solid fa-comment fa-fw
          url: https://api.wyblog.repl.co
        - name: 哔哩哔哩
          icon: 
          rows:
             - name: 1
               icon: fas fa-network-wired fa-fw
               url: tags/blibli/
             - name: 2
               icon: fas fa-network-wired fa-fw
               url: tags/blibli-page-2/           
        - name: 说说
          icon: fa-fw fas fa-envelope faa-tada
          url: shuoshuo/           
site_footer:
  layout: [aplayer, social, source, analytics, copyright]
  copyright: '[Copyright © Since 2017 Volantis Team](https://github.com/volantis-x/)'
  social:
    - img: volantis-static/media/org.volantis/icon/1322024-social-media/029-github.svg
      url: https://github.com/612901/

  message:
    enable: true
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_style/_plugins/fontcolor.styl
      default: fa-solid fa-info-circle light-blue
      quection: fa-solid fa-question-circle light-blue
    time:     # 默认持续时间
      default: 5000
      quection: 20000
    position: 'topRight'                 # 弹出位置 可选值：topRight, bottomRight, bottomLeft, topLeft, topCenter, bottomCenter, center
    transitionIn: 'bounceInLeft'         # 弹窗打开动画 可选值：bounceInLeft, bounceInRight, bounceInUp, bounceInDown, fadeIn, fadeInDown, fadeInUp, fadeInLeft, fadeInRight, flipInX
    transitionOut: 'fadeOutRight'        # 弹窗关闭动画 可选值：fadeOut, fadeOutUp, fadeOutDown, fadeOutLeft, fadeOutRight, flipOutX
    titleColor: 'var(--color-text)'      # 标题颜色
    messageColor: 'var(--color-text)'    # 消息颜色
    backgroundColor: 'var(--color-card)' # 默认背景色
    zindex: 2147483647                   # 层级
    copyright:                           # 是否在复制时弹出版权提示，影响范围：ctrl+c、代码块复制按钮、右键复制选项
      enable: true
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'far fa-copyright light-blue'
    aplayer:                              # 是否开启音乐通知；播放、暂停、失败 时的图标
      enable: true
      play: fa-solid fa-play
      pause: fa-solid fa-pause
    rightmenu:
      enable: true                        # 是否开启右键模块的消息通知
      notice: true                        # 唤醒原右键菜单的通知  
    
navbar:
  visiable: auto
  logo:
    img: 
    icon: 
    title: 无影博客
  search: 搜索你想知道的内容
  menu:
    - name: 首页
      icon: fa-light fa-home SUNFLOWER faa-vertical
      url: /
    - name: 分站
      icon: fa-light fa-rss CARROT faa-vertical
      rows:
        - name: Butterfly
          url: Butterfly/
        - name: Yun
          url: Yun/
    - name: 文章
      icon: fa-light fa-book-reader GREENSEA faa-vertical
      rows:
        - name: 分类
          icon: fa-light fa-folder-open TURQUOISE faa-vertical
          url: categories/
        - name: 标签
          icon: fa-light fa-tags PETERRIVE faa-vertical
          url: tags/
        - name: 归档
          icon: fa-light fa-archive GREENSEA faa-vertical
          url: archives/
    - name: 导航
      icon: fa-light fa-cube NEPHRITIS faa-vertical
      rows:
        - name: 关于
          icon: fa-light fa-info-circle SUNFLOWER faa-vertical
          url: about/
        - name: 留言板
          icon: fa-light fa-comment-alt-dots GREENSEA faa-vertical
          url: info/
        - name: hr
        - name: 追番
          icon: fa-light fa-video EMERALD faa-vertical
          url: bangumis/
        - name: 追剧
          icon: fa-light fa-video EMERALD faa-vertical
          url: cinemas/
        - name: hr
        - name: 友链
          icon: fa-light fa-link POMEGRANATE faa-vertical
          url: friends/
        - name: 朋友的文章
          icon: fa-light fa-user-friends ALIZARIN faa-vertical
          url: fcircle/
        - name: hr
        - name: BBTalk
          icon: fa-light fa-comments PETERRIVE faa-vertical
          url: bb/  
        - name: ArtiTalk
          icon: fa-light fa-comments PETERRIVE faa-vertical
          url: artitalk/
    - name: 功能
      icon: fa-light fa-tools ALIZARIN faa-vertical
      rows:
        - name: 深色模式
          icon: fa-light fa-moon POMEGRANATE faa-vertical
          toggle: darkmode
        - name: 背景音乐
          icon: fa-light fa-compact-disc EMERALD faa-vertical
        - name: hr  
        - name: RSS 订阅
          icon: fa-light fa-rss SUNFLOWER faa-vertical
          url: atom.xml
    - name: 更多 # 可自定义
      icon: fa-light fa-compass WISTERIA faa-vertical # 可自定义
      rows: 
        - name: Typecho
          icon: fa-light fa-blog ALIZARIN faa-vertical
          url: https://blog.sakurasep.club/
        - name: Halo
          icon: fa-light fa-blog ALIZARIN faa-vertical
          url: https://halo.sakurasep.club/
        - name: MX Space
          icon: fa-light fa-blog ALIZARIN faa-vertical
          url: https://space.sakurasep.site/
        - name: hr
        - name: Chevereto
          icon: fa-light fa-images EMERALD faa-vertical
          url: https://pic.sakurasep.top/
        - name: Oneindex
          icon: fa-light fa-images SUNFLOWER faa-vertical
          url: https://pic.sakurasep.club/
        - name: Cloudreve
          icon: fa-light fa-browser PETERRIVE faa-vertical
          url: https://cloud.sakurasep.club/
    - name: 开往
      icon: fa-light fa-subway PETERRIVE faa-ring faa-slow
      url: https://travellings.link
