custom_css:
  cursor:
      enable: true
  fontfamily:
    logofont:
      fontfamily: '庞门正道粗书体'
      name: '庞门正道粗书体'
      url: 'https://cdn.jsdelivr.net/gh/inkss/common@1/fonts/canva/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E7%B2%97%E4%B9%A6%E4%BD%93.woff2'
    bodyfont:
      fontfamily: 'SentyGoldenBell'
      name: 'SentyGoldenBell'
      url: 'https://cdn.jsdelivr.net/gh/inkss/common@1/fonts/canva/SentyGoldenBell.woff2'
    codefont:
      fontfamily: 'SentyTEA'
      name: 'SentyTEA'
      url: 'https://cdn.jsdelivr.net/gh/inkss/common@1/fonts/canva/SentyTEA.woff2'  

debug: ture
content_visibility: true
navbar:
  visiable: always
  logo: # choose [img] or [icon + title]
    img: '' # volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png
    icon: https://661111.github.io/media/images/custom-headerLogo.ico
    title: '天闲无影的博客'
  menu:
    - name: 分类
      icon: fa-solid fa-folder-open
      rows:  
        - name: gridea
          icon: fa-solid fa-folder-open
          url: tags/gridea/
        - name: bilbil
          icon: fa-solid fa-folder-open
          url: tags/blibli/
        - name: 学科
          icon: fa-solid fa-folder-open
          url: tags/学科/ 
        - name: bilbilpage2
          icon: fa-solid fa-folder-open
          url: tags/blibli-page-2/
        - name: 相册集
          icon: fa-solid fa-folder-open
          url: tags/相册/     
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 关于
      icon: fas fa-info-circle fa-fw
      rows:
        - name: 版权声明
          url: 2022/09/17/copyright/
        - name: 免责声明
          url: 2022/09/17/mian-ze-sheng-ming-1/
        - name: 关于本站
          url: 2022/09/24/list/
        - name: 关于
          url: /2022/08/20/about/
    - name: 小功能
      icon: fa-solid fa-link
      rows: 
        - name: 友链
          icon: fa-solid fa-link
          url: friends/
        - name: 朋友圈
          icon: fa-solid fa-feed
          url: links/
          rows:      
             - name: 朋友圈模板1
               icon: fa-solid fa-feed
               url: links/
             - name: 朋友圈模板2
               icon: fa-solid fa-feed
               url: fcircle/
        - name: 开往
          icon: fa-solid fa-subway
          url: https://travellings.link/
        - name: hr
        - name: homepage
          icon: fa-solid fa-subway
          url: /homepage/      
    - name: 更多
      icon: fa-solid fa-ellipsis-v
      rows:
        - name: 每日日报
          icon: fas fa-newspaper
          url: https://news.wyblog1.tk       
        - name: 音乐盒
          icon: fas fa-music
          url: https://api.wyblog.repl.co
        - name: 哔哩哔哩
          icon: fa-solid fa-comment fa-fw 
          rows:
             - name: 1
               icon: fa-solid fa-comment fa-fw 
               url: tags/blibli/
             - name: 2
               icon: fa-solid fa-comment fa-fw 
               url: tags/blibli-page-2/           
        - name: 说说
          icon: fa-fw iconfont icon-shejiao
          url: shuoshuo/
        - name: hr  
        - name: 深色模式
          icon: fa-solid fa-moon
          toggle: darkmode
        - name: 背景音乐
          icon: fa-solid fa-compact-disc   
          
site_footer:
  layout: [aplayer, social, bs, bq, wy, analytics, mz]
  bq: 博客内容遵循<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议</a>
  bs: 本网站由<a href="https://vercel.com" target="_blank">vercel</a>提供加速|本网站由<a href="https://github.com" target="_blank">github</a>提供代码存储|本网站由<a href="https://hexo.io/zh-cn/" target="_blank">hexo</a>提供博客框架|本网站以<a href="https://github.com/volantis-x/hexo-theme-volantis/" target="_blank">volantis</a>为主题
  wy: Copyright © Since 2021-2022 无影博客 All Rights Reserved
  analytics: >
    <span>本站总访问量为 <span id='busuanzi_value_site_pv'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 次</span>
    <span>访客数为 <span id='busuanzi_value_site_uv'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 人</span>
  mz: 无影博客
  tb: <p><i class="fa-solid fa-archive light-blue"></i>
  social:
    - img: volantis-static/media/org.volantis/icon/1322024-social-media/029-github.svg
      url: https://github.com/612901/
    - img: volantis-static/media/org.volantis/icon/1322024-social-media/006-youtube.svg  
      url: https://www.kuaishou.com/profile/3xh4ut4ekexbr7a
    - img: https://661111.github.io/media/images/custom-headerLogo.ico 
      url: /  
    - img: volantis-static/media/org.volantis/icon/1322024-social-media//017-picasa.svg
      url: https://7bu.top/login
    - img: volantis-static/media/org.volantis/icon/1322024-social-media/011-team-viewer.svg 
      url: https://gitee.com/wuyingblog/
      
  message:
    enable: true
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_style/_plugins/fontcolor.styl
      default: fa-solid fa-info-circle light-blue
      quection: fa-solid fa-question-circle light-blue
    time:     # 默认持续时间
      default: 5000
      quection: 20000
    position: 'topRight'                 # 弹出位置 可选值：topRight, bottomRight, bottomLeft, topLeft, topCenter, bottomCenter, center
    transitionIn: 'bounceInLeft'         # 弹窗打开动画 可选值：bounceInLeft, bounceInRight, bounceInUp, bounceInDown, fadeIn, fadeInDown, fadeInUp, fadeInLeft, fadeInRight, flipInX
    transitionOut: 'fadeOutRight'        # 弹窗关闭动画 可选值：fadeOut, fadeOutUp, fadeOutDown, fadeOutLeft, fadeOutRight, flipOutX
    titleColor: 'var(--color-text)'      # 标题颜色
    messageColor: 'var(--color-text)'    # 消息颜色
    backgroundColor: 'var(--color-card)' # 默认背景色
    zindex: 2147483647                   # 层级
    darkmode:
      enable: true
    copyright:                           # 是否在复制时弹出版权提示，影响范围：ctrl+c、代码块复制按钮、右键复制选项
      enable: true
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'far fa-copyright light-blue'
    aplayer:                              # 是否开启音乐通知；播放、暂停、失败 时的图标
      enable: true
      play: fa-solid fa-play
      pause: fa-solid fa-pause
    rightmenu:
      enable: true                        # 是否开启右键模块的消息通知
      notice: true                        # 唤醒原右键菜单的通知   
sidebar:
  position: left
  for_page: [qgroup, category, post, blogger, text, qrcode, guide, webinfo]
  for_post: [toc]
  lastupdate:
      class: lastupdate
      display: [desktop, cus-shadow]
      header:
        icon: fa-light fa-clock WISTERIA
        title: 最近更新
  donate:
    class: qrcode
    display: [desktop, mobile] # [desktop, mobile]
    height: 64px  # Automatic height if not set
    images:
      - https://cdn.jsdelivr.net/gh/612901/661111@main/R8%5D%409CBKKDK_T59HJ(NH(S2.png
  blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: https://661111.github.io/media/images/custom-headerLogo.ico
      title: 无影
      subtitle:
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: true      
  widget_library:
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-solid fa-list
        title: 本文目录
      list_number: true
      min_depth: 2
      max_depth: 5
    post:
      class: text
      display: [desktop, mobile] # [desktop, mobile]
      sticky: true
      header:
        icon: fa-leaf
        title: 公告
      content:
        - 'wyblog1.1版本'
        - '1.将侧边栏弄到左边 2.将原图片加载替换成windows4K图片'
        - '新年新气象,博客这几天会对网站的一些功能进行更新,到时,网站会以全新的形象展现给大家.'
        - '网站域名已更换新域名,新地址: [https://blog.wyblog1.tk](https://blog.wyblog1.tk),另外,本博客计划将会在2023.1.1开启右键自定义菜单.会开发出一些符合自己的美观'
        - '本站默认替换了右键菜单，可使用「Ctrl + 右键」唤醒原菜单博客已经开放右键,修改了一些UI.'
        - '本站主只是一个萌新,部分配置是博主去主题官方群询问得到的'
    # 文档导航
    webinfo:
      class: webinfo
      display: [desktop, mobile]
      header:
        icon: fa-solid fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: ture
          data: '2021/09/01'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: false
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          enable: true
          siteuv:
            text: '本站访客数：'
            unit: '人'
          sitepv:
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'
    guide:
      class: grid
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-solid fa-map-signs
        title: 分类导航
      fixed: ture # 固定宽度
      rows:
        - name: 友链
          icon: fa-solid fa-link
          url: /friends/
        - name: 朋友圈
          icon: fa-solid fa-feed
          url: /links/
        - name: 归档
          icon: fa-solid fa-archive
          url: /archives/
        - name: 音乐盒
          icon: fa-solid fa-compact-disc 
          url: https://api.wyblog.repl.co
        - name: 个人主页
          icon: fas fa-info-circle fa-fw
          url: https://wyblog1.tk 
        - name: 去追番吧
          icon: fa-solid fa-comment fa-fw 
          url: /bangumi/  
        - name: 留言板
          icon: fa-solid fa-comment fa-fw 
          url: /messages/  
        - name: 开往
          icon: fa-solid fa-subway
          url: https://travellings.now.sh/
        - name: 新冠疫情图
          icon: fas fa-newspaper
          url: /xg/
          
search:
  enable: true
  algolia:
    searchAsYouType: false
    placeholder: '输关键词后「回车」搜索' # The placeholder text of the input.
  meilisearch:
    placeholder: 'Search...'
    searchKey: '162d226211d1dd3c5a3dfedbefcb1d349c5d84f00ecc76397677879d8850c317'
    indexName: 'hexo'
    hostUrl: 'https://search.szyink.com/'
cover:
  enable: false
  height_scheme: full
  layout_scheme: dock
  display:
    home: true
    archive: true
    others: true
top:
  enable: false
  height_scheme: full
  layout_scheme: dock
  display:
    post: false 
