
debug: false
content_visibility: true
navbar:
  logo: # choose [img] or [icon + title]
    img: '' # volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png
    icon:
    title: 'Volantis 6 <sup style="color:#ff9800">alpha</sup>'
  menu:
    - name: 博客
      icon: fa-solid fa-rss
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      rows:  
        - name: gridea
          url: tags/gridea/
        - name: bilbil
          url: tags/blibli/
        - name: bilbil
          url: tags/blibli/
        - name: 学科
          url: tags/学科/ 
        - name: bilbilpage2
          url: tags/blibli-page-2/
        - name: 相册集
          url: tags/相册/     
    - name: 标签
      icon: fa-solid fa-tags
      url: tags/
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 友链
      icon: fa-solid fa-link
      rows:
        - name: 友链
          url: friends/
        - name: 朋友圈
          url: links/
    - name: 关于
      icon: fa-solid fa-info-circle
      url: about/

cover:
  # height_scheme: full # full, half
  title: 'Volantis'
  subtitle: '中文创作者社区'
  background: # https://bing.ioliu.cn/v1/rand?w=1920&h=1200
  features:
    - name: 博客
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg
      url: /
    - name: 文档
      img: volantis-static/media/twemoji/assets/svg/1f516.svg
      url: /v6/getting-started/
      target: _self
    - name: 示例
      img: volantis-static/media/twemoji/assets/svg/1f4af.svg
      url: /examples/
    - name: 帮助
      img: volantis-static/media/twemoji/assets/svg/1f4ac.svg
      url: /faqs/
    - name: 鸣谢
      img: volantis-static/media/twemoji/assets/svg/1f497.svg
      url: /contributors/
    - name: 归档
      img: volantis-static/media/twemoji/assets/svg/1f5c3.svg
      url: /archives/
    - name: 源码
      img: volantis-static/media/twemoji/assets/svg/1f9ec.svg
      url: https://github.com/volantis-x/hexo-theme-volantis/
      target: _self

