navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png # https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title:
  menu:
    - name: 首页
      icon: fa-solid fa-rss
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: tags/
      rows:  
        - name: gridea
          url: tags/gridea/
        - name: bilbil
          url: tags/blibli/
        - name: bilbil
          url: tags/blibli/
        - name: 学科
          url: tags/学科/ 
        - name: bilbilpage2
          url: tags/blibli-page-2/
        - name: 相册集
          url: tags/相册/     
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 友链
      icon: fa-solid fa-link
      rows:
        - name: 友链
          icon: fa-solid fa-play-circle
          url: friends/
        - name: 朋友圈
          icon: fa-solid fa-feed fa-fw
          url: links/
    - name: 关于
      icon: fa-solid fa-info-circle
      rows:
        - name: 版权声明
          url: 2022/09/17/copyright/
        - name: 免责声明
          url: 2022/09/17/mian-ze-sheng-ming-1/
        - name: 关于本站
          url: 2022/09/24/list/
        - name: 关于
          url: /2022/08/20/about/
    - name: 更多
      icon: fa-duotone fa-ellipsis-v fa-fw
      rows:
        - name: 音乐
          icon: fa-solid fa-play-circle
          url: https://api.wyblog.repl.co  
guide:
      class: grid
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-solid fa-map-signs
        title: 分类导航
      fixed: true # 固定宽度
      rows:
        - name: 朋友圈
          icon: fa-solid fa-feed fa-fw
          url: links/
        - name: 友链
          icon: fa-solid fa-play-circle
          url: friends/        
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, license, info, copyright]
  social:
    - icon: fas fa-envelope
      url: 32279882555@qq.com
    - icon: fab fa-github
      url: https://github.com/612901
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=63035382
  copyright: '[Copyright © 2021-2022 无影博客](/)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>' 
  
